# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Regridding ecosystem overview
author: Justus Magin
logo: logo.png
copyright: "2025"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 600

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/iaocea/regridding-ecosystem-overview
  path_to_book: docs
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
